name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - run: cargo build --release

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v3
        with:
          name: carbonrs-linux
          path: target/release/carbonrs

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - run: cargo build --release

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v3
        with:
          name: carbonrs-windows
          path: target/release/carbonrs.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - run: cargo build --release

      - name: Upload macOS Binary
        uses: actions/upload-artifact@v3
        with:
          name: carbonrs-macos
          path: target/release/carbonrs

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Prepare Release Assets
        run: |
          mkdir -p release_files
          cp artifacts/carbonrs-linux/mycli release_files/mycli-linux
          cp artifacts/carbonrs-windows/carbonrs.exe release_files/carbonrs.exe
          cp artifacts/carbonrs-macos/carbonrs release_files/carbonrs

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            release_files/carbonrs
            release_files/mycli-windows.exe
            release_files/mycli-macosv
